### ISSUE TITLE
Backporting to odoo 10

### ISSUE THREAD

**Issue by SamirSaidani** [andriisem/addons#3]
Hi,

I'm thrilled to see a holocracy module on odoo ! I'm working in a holocracy-powered opensource-oriented company, and I'm willing to test your module for our crew : I understand that the module was built for 12.0, according to the odoo appstore, does it work or need backporting on 10.0 ?

Thanks a lot for providing this module !

Do you intend to push it further ?

**Comment by andriisem** [comment]
Hi @samir-s

I added a branch for 10.0 it is a very primitive module and it should be improved

also, you can test here: 
http://78.47.165.98:68/
login: admin
password: 1234

Thanks)
